/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  academieYearId: number;
  archive: boolean;
  classeId: number;
  date: string;
  description: string;
  id?: number;
  programId: number;
  studentId: number;
}
