/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AcademieYearRequest } from './models/academie-year-request';
export type { AcademieYearResponse } from './models/academie-year-response';
export type { ClasseRequest } from './models/classe-request';
export type { ClasseResponse } from './models/classe-response';
export type { ProgramRequest } from './models/program-request';
export type { ProgramResponse } from './models/program-response';
export type { RegistrationRequest } from './models/registration-request';
export type { RegistrationResponse } from './models/registration-response';
export type { StudentRequest } from './models/student-request';
export type { StudentResponse } from './models/student-response';
