/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { StudentsService } from './services/students.service';
export { RegistrationsService } from './services/registrations.service';
export { ProgramsService } from './services/programs.service';
export { ClassesService } from './services/classes.service';
export { AcademieYearsService } from './services/academie-years.service';
