/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProgramRequest } from '../../models/program-request';
import { ProgramResponse } from '../../models/program-response';

export interface UpdateProgram$Params {
      body: ProgramRequest
}

export function updateProgram(http: HttpClient, rootUrl: string, params: UpdateProgram$Params, context?: HttpContext): Observable<StrictHttpResponse<ProgramResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProgram.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProgramResponse>;
    })
  );
}

updateProgram.PATH = '/programs';
