/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { deleteStudent } from '../fn/students/delete-student';
import { DeleteStudent$Params } from '../fn/students/delete-student';
import { getStudentById } from '../fn/students/get-student-by-id';
import { GetStudentById$Params } from '../fn/students/get-student-by-id';
import { getStudents } from '../fn/students/get-students';
import { GetStudents$Params } from '../fn/students/get-students';
import { saveStudent } from '../fn/students/save-student';
import { SaveStudent$Params } from '../fn/students/save-student';
import { StudentResponse } from '../models/student-response';
import { updateStudent } from '../fn/students/update-student';
import { UpdateStudent$Params } from '../fn/students/update-student';

@Injectable({ providedIn: 'root' })
export class StudentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getStudents()` */
  static readonly GetStudentsPath = '/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStudents()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudents$Response(params?: GetStudents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StudentResponse>>> {
    return getStudents(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStudents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudents(params?: GetStudents$Params, context?: HttpContext): Observable<Array<StudentResponse>> {
    return this.getStudents$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StudentResponse>>): Array<StudentResponse> => r.body)
    );
  }

  /** Path part for operation `updateStudent()` */
  static readonly UpdateStudentPath = '/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent$Response(params: UpdateStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
    return updateStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStudent(params: UpdateStudent$Params, context?: HttpContext): Observable<StudentResponse> {
    return this.updateStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponse>): StudentResponse => r.body)
    );
  }

  /** Path part for operation `saveStudent()` */
  static readonly SaveStudentPath = '/students';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveStudent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveStudent$Response(params: SaveStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
    return saveStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveStudent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveStudent(params: SaveStudent$Params, context?: HttpContext): Observable<StudentResponse> {
    return this.saveStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponse>): StudentResponse => r.body)
    );
  }

  /** Path part for operation `getStudentById()` */
  static readonly GetStudentByIdPath = '/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getStudentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById$Response(params: GetStudentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StudentResponse>> {
    return getStudentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getStudentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getStudentById(params: GetStudentById$Params, context?: HttpContext): Observable<StudentResponse> {
    return this.getStudentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StudentResponse>): StudentResponse => r.body)
    );
  }

  /** Path part for operation `deleteStudent()` */
  static readonly DeleteStudentPath = '/students/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStudent()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent$Response(params: DeleteStudent$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteStudent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStudent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStudent(params: DeleteStudent$Params, context?: HttpContext): Observable<void> {
    return this.deleteStudent$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
