/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationRequest } from '../../models/registration-request';
import { RegistrationResponse } from '../../models/registration-response';

export interface UpdateRegistration$Params {
      body: RegistrationRequest
}

export function updateRegistration(http: HttpClient, rootUrl: string, params: UpdateRegistration$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistrationResponse>> {
  const rb = new RequestBuilder(rootUrl, updateRegistration.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegistrationResponse>;
    })
  );
}

updateRegistration.PATH = '/registrations';
