services:
  postgres:
    container_name: postgres-scolaire
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scolaire-db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - scolaire-ms

volumes:
  postgres_data:
    driver: local

networks:
  scolaire-ms:
    driver: bridge