/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClasseRequest } from '../../models/classe-request';
import { ClasseResponse } from '../../models/classe-response';

export interface AddClasse$Params {
      body: ClasseRequest
}

export function addClasse(http: HttpClient, rootUrl: string, params: AddClasse$Params, context?: HttpContext): Observable<StrictHttpResponse<ClasseResponse>> {
  const rb = new RequestBuilder(rootUrl, addClasse.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClasseResponse>;
    })
  );
}

addClasse.PATH = '/classes';
