/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClasseResponse } from '../../models/classe-response';

export interface AssignSubjectToClasse$Params {
  classeId: number;
  subjectId: number;
}

export function assignSubjectToClasse(http: HttpClient, rootUrl: string, params: AssignSubjectToClasse$Params, context?: HttpContext): Observable<StrictHttpResponse<ClasseResponse>> {
  const rb = new RequestBuilder(rootUrl, assignSubjectToClasse.PATH, 'post');
  if (params) {
    rb.path('classeId', params.classeId, {});
    rb.path('subjectId', params.subjectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClasseResponse>;
    })
  );
}

assignSubjectToClasse.PATH = '/classes/{classeId}/assign-subject/{subjectId}';
