springdoc:
  default-produces-media-type: application/json

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scolaire-db?createDatabaseIfNotExist=true
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/logs.log

#Config for h2
#spring:
#  application:
#    name: stock-ms
#  datasource:
#    url: ${DB_URL:jdbc:h2:mem:stock-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
#    driverClassName: ${DB_DRIVER:org.h2.Driver}
#    username: ${DB_USER:user}
#    password: ${DB_PASSWORD:passer@123}
#  jpa:
#    database-platform: ${DB_USER:org.hibernate.dialect.H2Dialect}
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  h2:
#    console:
#      enabled: true